[fsgurl]
url = 'https://www.formulastudent.de/fsg/'
login_url = 'https://www.formulastudent.de/login'
account_url = 'https://www.formulastudent.de/my-account/overview/'

[debug]
performance_logger = false

[clickup]
api_server = 'https://api.clickup.com/api/v2'
